{
package parser

import "reflect"
import "fmt"
}

Input <- input:(sf ( Expression ) sf ln)* EOF {
    results := []any{}

    for _, item := range input.([]any) {
        results = append(results, item.([]any)[1].(any))
    }

    return results, nil
}

Expression <- exp:(MathOperation / Integer) {
    return exp, nil
}

MathOperation <- right:Expression sf (`+` / `-` / `/` / `*`) sf left:Expression

Integer <- [0-9]+

sf "spacefiller" <- [ \t]*

ln "linebreak" <- [\n\r]+

EOF<- !.
